### ISSUE TITLE
return original order of jQuery array.

### ISSUE THREAD

**Issue by MattyBalaam** [julianshapiro/blast#13]
I am using Blast and wondered if it is expected that the original sequence of an array is not honoured, instead blast returns according to position in the DOM.

Here is an illustration: http://jsfiddle.net/9gogkww5/

**Comment by MattyBalaam** [comment]
I have a workaround for now by storing positions before Blast, and then sorting: http://jsfiddle.net/9gogkww5/2/

**Comment by julianshapiro** [comment]
Unlikely to implement for time being, but will revisit shortly. Thank you, Mr. Balaam :)
