### ISSUE TITLE
Abbreviated first names

### ISSUE THREAD

**Issue by franciscop** [julianshapiro/blast#14]
When a first name is abbreviated, the library doesn't normally catch it. A good solution might be to add the following regex as an exception for this case:

    [A-Z][a-z]*\.\ [A-Z]

> In action: [Regex101.com](https://regex101.com/r/lW1nI6/2)

It accounts for all the instances of F. Presencia or similar first names abbreviations.

[Here a list of examples of first names](http://www.genealogyintime.com/dictionary/list-of-first-name-abbreviations.html), all follow this pattern.

**Comment by julianshapiro** [comment]
Thanks, Francis! I'm concerned, however, about the likelihood of matching false positives -- especially given that this type of abbreviation is fairly rare (as far as I know re. English, that is).

**Comment by franciscop** [comment]
I see that it might become a problem with sentences like:

    I like Martha. But she like Tom. Double fail in one line.

Also, I was [testing it in a fairly old](http://franciscop.github.io/learn/) book (Tales of Space and Time), so I might not encounter this problem in modern texts. Thank you for the reply.
