### ISSUE TITLE
Blast both words and sentences at same time?

### ISSUE THREAD

**Issue by alanhorizon** [julianshapiro/blast#16]
Hi Julian,

Gotta start with saying this is awesome work. Haven't seen anything that comes close to transforming a webpage of text into a DOM structure that can be manipulated at the word/sentence level. So thank you!

I can peer into source at some point, but off the top of your head, is it possible to use Blast, either as is or modified, such that I can manipulate text at the word level and at the sentence level at the same time? Not sure if that makes sense but let me try to explain in code:

```
<div>
    Hello World. How are you?
<div>
```
into:
```
<div class="blast-root">
  <div class="sentence-1">
    <span class="blast">Hello</span>
    <span class="blast">World.</span>
  </div>
  <div class="blast-sentence-2">
    <span class="blast">How</span>
    <span class="blast">are</span>
    <span class="blast">you?</span>
  </div>
</div>
```

Thanks also for still replying to issues and continuing to support this work!

**Comment by julianshapiro** [comment]
hey, alan :)

thanks for the kind words.

yeah, i believe you can simply blast by sentence then select all returned sentence elements and blast them by word. if it doesn't work let me know. feel free to through up an example on codepen/jsfiddle! i'll re-open if so.
