### ISSUE TITLE
Blast treats spaces between words as non-characters.

### ISSUE THREAD

**Issue by thegreenpizza** [julianshapiro/blast#8]
Blast treats spaces between words as non-characters. This causes the character delimiter to return improper indexes. Because of this, lining up character index data with blast's generated blast-indexes is very difficult. 

There should be an option to treat whitespace as characters in order to maintain the <i>actual</i> index of characters from start to finish in a string of text.

By the way... this could be handled simply (I think) by adding a "preserveWhitespace" option that would only apply to characters. Then, you could do this inside the delimiter creation section:

    case "character":
                    /* Matches every non-space character. */
                    /* Note: This is the slowest delimiter. However, its slowness is only noticeable when it's used on larger bodies of text (of over 500 characters) on <=IE8.
                       (Run Blast with opts.debug=true to monitor execution times.) */
                    if (opts.preserveWhitespace)
                        delimiterRegex = /(.)/;
                    else
                        delimiterRegex = /\S/;
                    break;

I don't know if "." is the best way to do this. Perhaps it should only preserve the actual space character.

As a sidenote, to render properly you would need to give white-space: pre|pre-line|pre-wrap to the blasted element to make the spaces not collapse in their own HTML elements.

@julianshapiro , did you consider any of this during initial development?

**Comment by julianshapiro** [comment]
Fixed. See new release. there's now an `all` delimiter type.
