### ISSUE TITLE
Strange interaction between Blast and Velocity on multiple divs

### ISSUE THREAD

**Issue by artemist** [julianshapiro/blast#9]
Hey, I've noticed a problem when you try to use the same function twice on 2 divs with the same class. I've made a demo on codepen here, illustrating the problem. The function only works on the last div. 

http://codepen.io/sdras/pen/8d7f8116818ec9ec00f8f82be65838d5

I forked your demo on delimiters, just so that we know for sure I'm using versions of jquery, velocity, velocity ui, and blast that do work in isolation.

**Comment by julianshapiro** [comment]
Fixed. See new release.
